// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Helpers;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230428204000_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("WebApi.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Enang Lawrence",
                            Position = "midfielder"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Banwo Omosan",
                            Position = "midfielder"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Awase Faustina",
                            Position = "defender"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Awase Clara",
                            Position = "forwarder"
                        });
                });

            modelBuilder.Entity("WebApi.Entities.PlayerSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Skill")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerSkills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PlayerId = 1,
                            Skill = "strength",
                            Value = 70
                        },
                        new
                        {
                            Id = 2,
                            PlayerId = 1,
                            Skill = "stamina",
                            Value = 90
                        },
                        new
                        {
                            Id = 3,
                            PlayerId = 2,
                            Skill = "strength",
                            Value = 50
                        },
                        new
                        {
                            Id = 4,
                            PlayerId = 2,
                            Skill = "stamina",
                            Value = 2
                        },
                        new
                        {
                            Id = 5,
                            PlayerId = 3,
                            Skill = "defense",
                            Value = 60
                        },
                        new
                        {
                            Id = 6,
                            PlayerId = 3,
                            Skill = "speed",
                            Value = 80
                        },
                        new
                        {
                            Id = 7,
                            PlayerId = 4,
                            Skill = "attack",
                            Value = 20
                        },
                        new
                        {
                            Id = 8,
                            PlayerId = 4,
                            Skill = "speed",
                            Value = 70
                        });
                });

            modelBuilder.Entity("WebApi.Entities.PlayerSkill", b =>
                {
                    b.HasOne("WebApi.Entities.Player", "Player")
                        .WithMany("PlayerSkills")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("WebApi.Entities.Player", b =>
                {
                    b.Navigation("PlayerSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
